### ISSUE TITLE
The bed list apis don't have a summary to indicate number of beds, rooms, area in a shelter

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#3] opened 2020-12-01 22:02 UTC
The bed list apis don't have a summary to indicate number of beds, rooms, area in a shelter

**Comment by suryayadavalli** [comment] 2020-12-11 08:40
#4  will address this change as well. No additional effort is required.

**Comment by eric-jahn** [comment] 2020-12-11 17:31
duplicate of #4. closing.

**Closed as completed by eric-jahn** 2020-12-11 17:31 UTC
